version: "3.8"

services:
  # Traefik 2 - Reverse Proxy
  wgeasy:
    image: weejewel/wg-easy:latest
    networks:
      - default
      - traefik_proxy
    environment:
      - PASSWORD=${WGEASY_PASSWORD}
      - WG_HOST=${WG_HOST}
      # - WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth1 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.202207__wgeasy.entrypoints=websecure
      - traefik.http.routers.202207__wgeasy.rule=Host(`${WG_HOST}`)
      - traefik.http.routers.202207__wgeasy.tls.certresolver=leresolver
      - traefik.http.services.202207__wgeasy-service.loadbalancer.server.port=51821
      - com.centurylinklabs.watchtower.enable=true

########################### NETWORKS
networks:
  traefik_proxy:
    external: true
